Repository yeatmanlab/roar-dashboard, pull requests merged in 2024-10, with the labels that each got.

#757 Migrate Create Administration page to composable TanStack queries
  src/components/CreateAdministration.vue
  src/components/TaskPicker.vue
  src/composables/mutations/useUpsertAdministrationMutation.js
  src/composables/queries/useAdministrationsQuery.js
  src/composables/queries/useAdministrationsQuery.test.js
  src/composables/queries/useAdministrationsStatsQuery.js
  src/composables/queries/useAdministrationsStatsQuery.test.js
  src/composables/queries/useClassesQuery.js
  src/composables/queries/useDistrictsListQuery.test.js
  src/composables/queries/useDistrictsQuery.js
  src/composables/queries/useDistrictsQuery.test.js
  src/composables/queries/useDsgfOrgQuery.js
  src/composables/queries/useDsgfOrgQuery.test.js
  src/composables/queries/useFamiliesQuery.js
  src/composables/queries/useFamiliesQuery.test.js
  src/composables/queries/useGroupsListQuery.test.js
  src/composables/queries/useGroupsQuery.js
  src/composables/queries/useGroupsQuery.test.js
  src/composables/queries/useLegalDocsQuery.test.js
  src/composables/queries/useOrgQuery.test.js
  src/composables/queries/useOrgUsersQuery.js
  src/composables/queries/useOrgUsersQuery.test.js
  src/composables/queries/useSchoolsQuery.js
  src/composables/queries/useSchoolsQuery.test.js
  src/composables/queries/useUserAssignmentsQuery.js
  src/composables/queries/useUserAssignmentsQuery.test.js
  src/composables/queries/useUserClaimsQuery.js
  src/composables/queries/useUserClaimsQuery.test.js
  src/composables/queries/useUserDataQuery.js
  src/composables/queries/useUserDataQuery.test.js
  src/composables/queries/useUserRunPageQuery.js
  src/composables/queries/useUserStudentDataQuery.js
  src/composables/queries/useUserStudentDataQuery.test.js
  src/constants/mutationKeys.js
  src/constants/routes.js
  src/helpers/hasArrayEntries.js
  src/helpers/hasArrayEntries.test.js
  src/helpers/query/runs.js
  src/helpers/query/users.js
  src/helpers/query/utils.js
Labels: enhancement

#835 Replace existing sign-out method with query mutation
  src/components/NavBar.vue
  src/composables/mutations/useSignOutMutation.js
  src/composables/queries/useUserClaimsQuery.js
  src/composables/queries/useUserClaimsQuery.test.js
  src/composables/queries/useUserDataQuery.js
  src/composables/queries/useUserDataQuery.test.js
  src/composables/useInactivityTimeout/useInactivityTimeout.js
  src/composables/useInactivityTimeout/useInactivityTimeout.test.js
  src/constants/mutationKeys.js
  src/constants/routes.js
  src/containers/SessionTimer/SessionTimer.vue
  src/pages/HomeParticipant.vue
  src/router/index.js
  src/store/auth.js
Labels: enhancement

#837 Combine `ClassLink` and `Clever` into single refactored SSO landing page
  package-lock.json
  package.json
  src/App.vue
  src/components/CardAdministration.vue
  src/components/views/LinkAccountsView.vue
  src/composables/useSSOAccountReadinessVerification.js
  src/composables/useSSOAccountReadinessVerification.test.js
  src/constants/auth.js
  src/constants/routes.js
  src/pages/HomeSelector.vue
  src/pages/SSOAuthPage.vue
  src/pages/SignIn.vue
  src/router/index.js
  src/store/auth.js
Labels: enhancement

#840 Migrate tasks dictionary from auth store to query composable
  src/App.vue
  src/components/CardAdministration.vue
  src/components/reports/DistributionChartFacet.vue
  src/components/reports/DistributionChartOverview.vue
  src/components/reports/DistributionChartSupport.vue
  src/components/reports/IndividualScoreReportTask.vue
  src/components/reports/tasks/TaskReport.vue
  src/composables/queries/useTasksDictionaryQuery.js
  src/composables/queries/useTasksDictionaryQuery.test.js
  src/pages/ProgressReport.vue
  src/pages/ScoreReport.vue
  src/pages/StudentReport.vue
  src/store/auth.js
Labels: enhancement

#790 Add archived: false to queries for users and orgs
  firebase/LEVANTE/admin/firestore.rules
  firebase/LEVANTE/assessment/firestore.rules
  firebase/admin/firestore.indexes.json
  firebase/admin/firestore.rules
  firebase/assessment/firestore.rules
  package-lock.json
  package.json
  src/App.vue
  src/components/CardAdministration.vue
  src/components/ListUsers.vue
  src/components/NavBar.vue
  src/helpers/query/administrations.js
  src/helpers/query/assignments.js
  src/helpers/query/orgs.js
  src/helpers/query/users.js
  src/helpers/query/utils.js
  src/pages/HomeAdministrator.vue
  src/pages/HomeParticipant.vue
  src/pages/HomeSelector.vue
  src/pages/ScoreReport.vue
  src/pages/SignIn.vue
Labels: enhancement

#841 Migrate administration deletion to TanStack mutation
  src/components/CardAdministration.vue
  src/composables/mutations/useDeleteAdministrationMutation.js
  src/composables/mutations/useDeleteAdministrationMutation.test.js
  src/constants/mutationKeys.js
Labels: enhancement

#850 Update app launching behavior
  src/components/tasks/TaskCrowding.vue
  src/components/tasks/TaskFluency.vue
  src/components/tasks/TaskLetter.vue
  src/components/tasks/TaskLevante.vue
  src/components/tasks/TaskMEP.vue
  src/components/tasks/TaskMultichoice.vue
  src/components/tasks/TaskPA.vue
  src/components/tasks/TaskRan.vue
  src/components/tasks/TaskSRE.vue
  src/components/tasks/TaskSWR.vue
  src/components/tasks/TaskVocab.vue
Labels: bug

#845 Resolve merge conflicts for TanStack composables
  firebase/LEVANTE/admin/firestore.rules
  firebase/LEVANTE/assessment/firestore.rules
  firebase/admin/firestore.indexes.json
  firebase/admin/firestore.rules
  firebase/assessment/firestore.rules
  package-lock.json
  package.json
  src/App.vue
  src/components/CardAdministration.vue
  src/components/ListUsers.vue
  src/components/NavBar.vue
  src/composables/queries/useAdministrationsListQuery.js
  src/constants/orgTypes.js
  src/helpers/query/administrations.js
  src/helpers/query/assignments.js
  src/helpers/query/orgs.js
  src/helpers/query/users.js
  src/helpers/query/utils.js
  src/pages/HomeAdministrator.vue
  src/pages/HomeParticipant.vue
  src/pages/ScoreReport.vue
  src/pages/SignIn.vue
Labels: enhancement

#856 Component Tests for RoarDataTable
  .env.example.test
  .gitmodules
  cypress/component/components/RoarDataTable.cy.js
  cypress/component/components/slots/FilterBar.cy.js
  cypress/e2e/participant/default-tests/playOptionalGames.cy.js
  cypress/e2e/participant/old-tests/playButtonGames.cy.js
  cypress/e2e/partner-admin/default-tests/testScoreReportFiltering.cy.js
  cypress/e2e/pre-release-tests/generatePrereleaseTests.cy.js
  cypress/fixtures/component/roar-data-table/dataTemplate.js
  cypress/fixtures/component/roar-data-table/orgInfo.js
  cypress/fixtures/component/roar-data-table/partnerTestAdministration.js
  cypress/fixtures/component/roar-data-table/props/columns.js
  cypress/fixtures/component/roar-data-table/props/dataRandomized.js
  cypress/fixtures/component/roar-data-table/props/lazyPreSorting.js
  cypress/fixtures/component/roar-data-table/schools.js
  cypress/fixtures/component/roar-data-table/scores.js
  cypress/fixtures/component/roar-data-table/userClaims.js
  cypress/fixtures/participant/buttonGamesList.js
  cypress/fixtures/participant/optionalGamesList.js
  cypress/fixtures/super-admin/generatedTestTemplate.js
  cypress/fixtures/super-admin/taskTestSpecs.js
  cypress/fixtures/super-admin/testStudentData.csv
  cypress/fixtures/testStudentData.csv
  cypress/support/helper-functions/component-test/generateRandomData.js
  cypress/support/helper-functions/roar-vocab/languageOptions.js
  src/components/RoarDataTable.vue
  src/components/slots/FilterBar.vue
  src/composables/useFilteredTableData.js
  src/pages/ScoreReport.vue
Labels: test-creation

#868 Resolve merge conflicts for TanStack composables
  .env.example.test
  .gitmodules
  cypress/component/components/RoarDataTable.cy.js
  cypress/component/components/slots/FilterBar.cy.js
  cypress/e2e/participant/default-tests/playOptionalGames.cy.js
  cypress/e2e/participant/old-tests/playButtonGames.cy.js
  cypress/e2e/partner-admin/default-tests/testScoreReportFiltering.cy.js
  cypress/e2e/pre-release-tests/generatePrereleaseTests.cy.js
  cypress/fixtures/component/roar-data-table/dataTemplate.js
  cypress/fixtures/component/roar-data-table/orgInfo.js
  cypress/fixtures/component/roar-data-table/partnerTestAdministration.js
  cypress/fixtures/component/roar-data-table/props/columns.js
  cypress/fixtures/component/roar-data-table/props/dataRandomized.js
  cypress/fixtures/component/roar-data-table/props/lazyPreSorting.js
  cypress/fixtures/component/roar-data-table/schools.js
  cypress/fixtures/component/roar-data-table/scores.js
  cypress/fixtures/component/roar-data-table/userClaims.js
  cypress/fixtures/participant/buttonGamesList.js
  cypress/fixtures/participant/optionalGamesList.js
  cypress/fixtures/super-admin/generatedTestTemplate.js
  cypress/fixtures/super-admin/taskTestSpecs.js
  cypress/fixtures/super-admin/testStudentData.csv
  cypress/fixtures/testStudentData.csv
  cypress/support/helper-functions/component-test/generateRandomData.js
  cypress/support/helper-functions/roar-vocab/languageOptions.js
  src/components/RoarDataTable.vue
  src/components/slots/FilterBar.vue
  src/composables/useFilteredTableData.js
  src/pages/ScoreReport.vue
Labels: enhancement

#765 Export combination of Score and Progress Report
  cypress/e2e/partner-admin/default-tests/exportSelectedScoreReport.cy.js
  src/pages/ScoreReport.vue
Labels: enhancement

#867 Fix error handling in `fetchDocById` helper
  src/components/auth/RegisterStudent.vue
  src/helpers/query/utils.js
Labels: bug

#858 Changing Syntax name on game tabs
  cypress/e2e/pre-release-tests/testOpenAdministrations.cy.js
  cypress/support/helper-functions/roar-syntax/languageOptions.js
  src/translations/en/en-componentTranslations.json
  src/translations/en/us/en-us-componentTranslations.json
Labels: impact: low, effort: low, design-alignment

#874 Rolling back Levante core tasks from 18 to 16
  package-lock.json
  package.json
Labels: bug

#806 E2E for signUp code invitation
  .env.example.test
  .github/workflows/cypress-partner-admin-tests.yml
  cypress.config.cjs
  cypress/e2e/partner-admin/default-tests/parentSignUpInvitationCode.cy.js
  cypress/support/commands.js
  src/components/ListOrgs.vue
  src/components/auth/RegisterStudent.vue
  src/constants/routes.js
Labels: test-creation

#884 Fix administration selection
  src/pages/HomeParticipant.vue
Labels: bug

#888 Fix loading of administrator administrations
  src/pages/HomeAdministrator.vue
Labels: bug

#889 Fix participant homepage loading state
  src/pages/HomeParticipant.vue
  src/pages/HomeSelector.vue
Labels: bug

#864 Fix 'view by school' distribution graph
  src/pages/ScoreReport.vue
Labels: bug

#895 Fix Score Reports Not Populating Correctly
  src/composables/useFilteredTableData.js
  src/pages/HomeSelector.vue
  src/pages/ScoreReport.vue
Labels: bug, urgency: high, impact: medium

#904 Update roar-multichoice Packge to 1.11.5
  .editorconfig
  .gitignore
  package-lock.json
  package.json
Labels: task-update

#911 enh/Auto Add Pull Requests to QA Template
  .github/workflows/add-pull-request-to-qa-template.yml
Labels: enhancement, urgency: low, impact: medium

#920 Import PvChart on the card administration component
  src/components/CardAdministration.vue
Labels: bug

#921 Enforce `vue/no-undef-components` ESLint rule
  .eslintrc.json
  package-lock.json
  src/pages/LEVANTE/UserSurvey.vue
  vite.config.js
Labels: enhancement

#922 Updating apps to not include jscat caret
  package-lock.json
  package.json
Labels: dependencies
