Repository yeatmanlab/roar-dashboard, pull requests merged in 2024-11, with the labels that each got.

#928 Fix Game Tabs Being Cut Off on Large Screens
  package-lock.json
  src/assets/styles/components/tabview.scss
  src/assets/styles/theme-tailwind.css
  src/components/GameTabs.vue
Labels: urgency: low, impact: low, design-alignment, [qa] low priority, [qa] user interface, [qa] in progress, env: dev

#932 simplify assent/consent title
  cypress/e2e/participant/default-tests/checkLegalDoc.cy.js
  src/components/ConsentModal.vue
  src/translations/en/en-componentTranslations.json
  src/translations/en/us/en-us-componentTranslations.json
  src/translations/es/co/es-co-componentTranslations.json
  src/translations/es/es-componentTranslations.json
Labels: bug

#945 Updating SWR SRE an MULTICHOICE
  package-lock.json
  package.json
Labels: task-update

#950 Family Signup Form Styling Update
  cypress/e2e/partner-admin/default-tests/parentSignUpInvitationCode.cy.js
  src/assets/styles/routes/register.scss
  src/components/auth/RegisterChildren.vue
  src/components/auth/RegisterParent.vue
  src/pages/RegisterFamilyUsers.vue
  src/router/index.js
Labels: enhancement, design-alignment
