Repository yeatmanlab/roar-dashboard, pull requests merged in 2024-12, with the labels that each got.

#978 Change Roar - Inference to ROAR - Inference
  src/translations/en/en-componentTranslations.json
  src/translations/en/us/en-us-componentTranslations.json
  src/translations/es/es-componentTranslations.json
Labels: [qa] low priority

#985 Inference Update
  package-lock.json
  package.json
  src/helpers/reports.js
Labels: bug, [qa] high priority

#971 Refactor `<NavBar />` component
  .eslintrc.json
  cypress.config.cjs
  cypress/component/components/NavBar.cy.js
  cypress/e2e/partner-admin/default-tests/logout.spec.cy.js
  cypress/support/commands.js
  package-lock.json
  package.json
  src/App.vue
  src/components/NavBar.vue
  src/components/NavBar/NavBar.cy.js
  src/components/NavBar/NavBar.vue
  src/components/NavBar/index.js
  src/containers/Navigation/Navigation.test.js
  src/containers/Navigation/Navigation.vue
  src/test-support/mocks/mockUserClaims.js
Labels: enhancement, [qa] low priority, [qa] user interface

#973 Refactor component testing infrastructure
  .github/workflows/cypress-component-tests.yml
  cypress/support/commands.js
  cypress/support/component.js
  cypress/support/utils.js
  src/components/FilterBar/FilterBar.cy.js
  src/components/FilterBar/FilterBar.vue
  src/components/FilterBar/index.js
  src/components/ListOrgs.vue
  src/components/ListUsers.vue
  src/components/RoarDataTable/RoarDataTable.cy.js
  src/components/RoarDataTable/RoarDataTable.vue
  src/components/RoarDataTable/index.js
  src/components/reports/SubscoreTable.vue
  src/pages/ProgressReport.vue
  src/pages/ScoreReport.vue
  src/router/index.js
Labels: enhancement

#968 Update ROAV-Crowding version to 1.1.31
  package-lock.json
  package.json
Labels: [qa] high priority

#966 Update MEP version to 1.1.35
  package-lock.json
  package.json
Labels: [qa] high priority
