Repository yeatmanlab/roar-dashboard, pull requests merged in 2024-09, with the labels that each got.

#773 Store State of Show Optional Assessments
  cypress/e2e/participant/default-tests/playOptionalGames.cy.js
  cypress/support/commands.js
  src/pages/HomeParticipant.vue
  src/store/auth.js
Labels: impact: low, design-alignment

#772 Fix score and progress reports not loading
  package-lock.json
  package.json
  src/pages/ProgressReport.vue
  src/pages/ScoreReport.vue
Labels: bug

#771 fix/Terms of Service Popup
  src/pages/HomeSelector.vue
Labels: bug

#770 Update language on register user dropdown
  src/pages/RegisterStudents.vue
Labels: bug

#774 Restore default sort
  src/components/RoarDataTable.vue
  src/pages/ProgressReport.vue
  src/pages/ScoreReport.vue
Labels: bug

#779 Fix test Open Admins
  cypress/fixtures/generatedTestTemplate.js
  cypress/support/commands.js
  cypress/support/helper-functions/roar-sre/sreHelpers.js
Labels: bug

#778 Extend `useUserType` with super admin capability check
  src/composables/useUserType.js
  src/composables/useUserType.test.js
  src/constants/auth.js
  src/pages/HomeSelector.vue
Labels: enhancement

#780 Fix Test Open Admins x2
  cypress/fixtures/generatedTestTemplate.js
  cypress/support/commands.js
Labels: bug

#784 test admins with no optional assessments
  cypress/fixtures/generatedTestTemplate.js
Labels: bug

#782 Migrate Administrator homepage to composable TanStack queries
  src/composables/queries/useAdministrationsQuery.js
  src/constants/queryKeys.js
  src/helpers/query/administrations.js
  src/pages/HomeAdministrator.vue
Labels: enhancement

#760 Migrate List Organisations page to composable TanStack queries
  src/components/ListOrgs.vue
  src/composables/queries/useOrgsTableQuery.js
  src/constants/auth.js
  src/constants/queryKeys.js
  src/helpers/query/orgs.js
Labels: enhancement

#775 Migrate List Users page to composable TanStack queries
  src/components/ListUsers.vue
  src/composables/queries/useOrgUsersQuery.js
  src/composables/queries/useOrgUsersQuery.test.js
  src/constants/queryKeys.js
Labels: enhancement

#776 Migrate Manage Tasks and Manage Variants pages to composable TanStack queries
  src/components/CreateAdministration.vue
  src/components/tasks/ManageTasks.vue
  src/components/tasks/ManageVariants.vue
  src/composables/mutations/useAddTaskMutation.js
  src/composables/mutations/useAddTaskMutation.test.js
  src/composables/mutations/useAddTaskVariantMutation.js
  src/composables/mutations/useUpdateTaskMutation.js
  src/composables/mutations/useUpdateTaskMutation.test.js
  src/composables/mutations/useUpdateTaskVariantMutation.js
  src/composables/queries/useAdministrationVariantsQuery.js
  src/composables/queries/useTaskVariantsQuery.js
  src/composables/queries/useTaskVariantsQuery.test.js
  src/composables/queries/useTasksQuery.js
  src/composables/queries/useTasksQuery.test.js
  src/constants/mutationKeys.js
  src/constants/queryKeys.js
Labels: enhancement

#777 Migrate Offline Settings to composable TanStack queries
  src/components/views/OfflineSettings.vue
  src/composables/mutations/useUpdateUserMutation.js
  src/composables/mutations/useUpdateUserMutation.test.js
  src/composables/queries/useUserDataQuery.test.js
  src/constants/mutationKeys.js
Labels: enhancement

#792 Fix App Check `debugToken` conditional for Cypress environment
  src/config/firebaseRoar.js
Labels: bug

#738 Edit Orgs
  src/components/EditOrgsForm.vue
  src/components/ListOrgs.vue
  src/constants/toasts.js
Labels: enhancement

#793 Add fallback values before calling the forEach method
  package-lock.json
  package.json
  src/components/CardAdministration.vue
Labels: bug

#785 Migrate Participant Homepage to composable TanStack queries
  src/components/tasks/ManageTasks.vue
  src/components/views/OfflineSettings.vue
  src/composables/queries/useAdministrationsListQuery.js
  src/composables/queries/useAdministrationsQuery.js
  src/composables/queries/useSurveyResponsesQuery.js
  src/composables/queries/useSurveyResponsesQuery.test.js
  src/composables/queries/useTasksQuery.js
  src/composables/queries/useTasksQuery.test.js
  src/composables/queries/useUserAssignmentsQuery.js
  src/composables/queries/useUserAssignmentsQuery.test.js
  src/constants/firebase.js
  src/constants/queryKeys.js
  src/helpers/query/assignments.js
  src/helpers/query/tasks.js
  src/helpers/query/utils.js
  src/pages/HomeAdministrator.vue
  src/pages/HomeParticipant.vue
  vitest.config.js
Labels: enhancement

#798 Fix Score Report Headers
  src/components/RoarDataTable.vue
  src/pages/ScoreReport.vue
Labels: design-alignment

#807 Update ROAV-Ran version to 1.0.30
  package-lock.json
  package.json
Labels: task-update

#803 Update MEP version to 1.1.22
  package-lock.json
  package.json
Labels: task-update

#800 Update ROAV-Crowding version to 1.1.15
  package-lock.json
  package.json
Labels: task-update

#816 Make TanStack Query dev tools load conditionally
  .github/workflows/firebase-hosting-staging.yml
  src/App.vue
Labels: enhancement

#824 Update ROAV-Crowding version to 1.1.16
  package-lock.json
  package.json
Labels: task-update
