Repository yeatmanlab/roar-dashboard, pull requests merged in 2025-03, with the labels that each got.

#1059 Fix game tabs selection
  src/components/GameTabs.vue
Labels: bug

#1050 Update roam-apps version to 1.0.12
  cypress/fixtures/super-admin/taskTestSpecs.js
  cypress/support/helper-functions/roam-apps/languageOptions.js
  cypress/support/helper-functions/roam-apps/roamHelpers.js
  package-lock.json
  package.json
  src/components/reports/TableScoreTag.vue
  src/helpers/reports.js
  src/pages/ScoreReport.vue
Labels: task-update

#1067 External Tasks url param PID
  src/components/GameTabs.vue
Labels: bug

#1068 Fix: Raw Scores display for Core-Math
  src/pages/ScoreReport.vue
Labels: bug

#1066 ROAR - ReadAloud
  firebase.json
  firebase/admin/firestore.indexes.json
  package-lock.json
  package.json
  src/components/tasks/TaskReadAloud.vue
  src/containers/Navigation/Navigation.vue
  src/helpers/reports.js
  src/pages/ScoreReport.vue
  src/router/index.js
  vite.config.js
Labels: task-creation

#1070 Remove external filters from Score reports
  src/components/FilterBar/FilterBar.cy.js
  src/components/FilterBar/FilterBar.vue
  src/components/FilterBar/index.js
  src/components/RoarDataTable/RoarDataTable.vue
  src/composables/useFilteredTableData.js
  src/helpers/query/assignments.js
  src/pages/ProgressReport.vue
  src/pages/ScoreReport.vue
Labels: enhancement, design-alignment

#1074 fixing paths for read-aloud
  firebase/admin/firestore.indexes.json
Labels: bug

#1076 Use dev headers for local environment
  vite.config.js
Labels: bug

#1084 Add missing token to Firebase deploy action
  .github/actions/deploy/action.yml
  .github/workflows/ci.yml
Labels: bug

#1082 Update Levante Core Tasks
  .github/workflows/ci.yml
  package-lock.json
  package.json
Labels: bug, urgency: high, task-update
