Repository yeatmanlab/roar-dashboard, pull requests merged in 2025-06, with the labels that each got.

#1232 Improve pre-commit hook configuration
  .husky/pre-commit
  .lintstagedrc
  .prettierrc
  package-lock.json
  package.json
Labels: enhancement

#1233 Add autocomplete attribute to password inputs
  src/components/ListUsers.vue
  src/components/auth/RegisterChildren.vue
  src/components/auth/RegisterParent.vue
  src/components/auth/SignIn.vue
  src/components/views/PasswordView.vue
  src/pages/SignIn.vue
Labels: enhancement

#1235 [FIX] Query for CSV Admin Orgs
  src/components/OrgPicker.vue
  src/helpers/query/orgs.js
  src/pages/RegisterStudents.vue
Labels: bug

#1236 Bump `vue` from v3.2.25 to v3.5.16
  package-lock.json
  package.json
Labels: dependencies

#1230 [ENH] Refactor `HomeParent` to allow display of multiple assignments per card
  src/components/HomeParentStudentView.vue
  src/components/StudentCard.vue
  src/composables/queries/useMultipleUserAssignmentsQuery.js
  src/constants/queryKeys.js
  src/pages/HomeParent.vue
  src/pages/HomeParticipant.vue
Labels: [qa] medium priority

#1229 Introduce presets for Administration Dates
  src/components/AdministrationDatePicker/AdministrationDatePicker.test.js
  src/components/AdministrationDatePicker/AdministrationDatePicker.vue
  src/components/AdministrationDatePicker/index.js
  src/components/AdministrationDatePicker/presets.js
  src/components/AdministrationDatePicker/presets.test.js
  src/components/CreateAdministration.vue
  src/components/Form/DateInput/DateInput.test.js
  src/components/Form/DateInput/DateInput.vue
  src/components/Form/DateInput/index.js
  src/components/TaskPicker/TaskPicker.vue
  src/components/TaskPicker/index.js
  src/components/TaskPicker/taskPickerUtils.js
  src/components/VariantCard/EditVariantDialog.vue
  src/components/VariantCard/VariantCard.vue
  src/components/VariantCard/index.js
  src/styles.css
Labels: enhancement
