Repository yeatmanlab/roar-dashboard, pull requests merged in 2025-04, with the labels that each got.

#1085 Temporarily re-introduce deployments to legacy staging environment
  .github/workflows/deploy-legacy-staging.yml
  firebase/admin/firebase.staging-legacy.json
Labels: enhancement

#1086 Add missing `dotenvx` private keys for deploy steps
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-staging.yml
Labels: enhancement

#1087 Add missing private key for legacy staging deployments
  .github/workflows/deploy-legacy-staging.yml
Labels: enhancement

#1088 Fix private key env var name for legacy staging deployments
  .github/workflows/deploy-legacy-staging.yml
Labels: bug

#1080 Update roam-apps version to 1.2.3
  package-lock.json
  package.json
Labels: task-update, [qa] medium priority

#1122 Update MEP version to 1.2.0
  package-lock.json
  package.json
Labels: task-update

#1130 Update roam-apps version to 1.2.7
  cypress/support/helper-functions/roam-apps/roamHelpers.js
  package-lock.json
  package.json
Labels: task-update, [qa] medium priority

#1131 Update Letter version to 3.0.1
  package-lock.json
  package.json
Labels: task-update, [qa] medium priority

#1134 Update PA version to 2.2.5
  cypress/e2e/participant/default-tests/assessments/playPA.cy.js
  cypress/support/commands.js
  cypress/support/helper-functions/roar-pa/paHelpers.js
  package-lock.json
  package.json
Labels: task-update, [qa] medium priority

#1137 Update SWR version to 1.13.1
  package-lock.json
  package.json
Labels: task-update, [qa] medium priority

#1144 Update Levante Core Tasks 1.0.0-beta.39
  package-lock.json
  package.json
Labels: bug, task-update, [qa] medium priority

#1132 Update Multichoice version to 1.11.8
  package-lock.json
  package.json
Labels: task-update, [qa] medium priority

#1138 Update SRE version to 1.16.1
  package-lock.json
  package.json
Labels: task-update, [qa] medium priority

#1166 Update REST Config
  package-lock.json
  package.json
  src/components/CreateAdministration.vue
  src/components/CreateAdministrator.vue
  src/components/CreateOrgs.vue
  src/components/EditOrgsForm.vue
  src/components/EditUsersForm.vue
  src/components/ListOrgs.vue
  src/components/ListUsers.vue
  src/components/OrgPicker.vue
  src/components/modals/EditUsers.vue
  src/components/modals/RoarModal.vue
  src/components/reports/SubscoreTable.vue
  src/components/tasks/ManageTasks.vue
  src/components/tasks/ManageVariants.vue
  src/components/tasks/TaskCrowding.vue
  src/components/tasks/TaskLetter.vue
  src/components/tasks/TaskLevante.vue
  src/components/tasks/TaskMEP.vue
  src/components/tasks/TaskMultichoice.vue
  src/components/tasks/TaskPA.vue
  src/components/tasks/TaskRan.vue
  src/components/tasks/TaskReadAloud.vue
  src/components/tasks/TaskRoam.vue
  src/components/tasks/TaskSRE.vue
  src/components/tasks/TaskSWR.vue
  src/components/tasks/TaskVocab.vue
  src/components/views/LinkAccountsView.vue
  src/components/views/UserInfoView.vue
  src/containers/ManageTasks/components/UpdateTaskForm.vue
  src/containers/Navigation/Navigation.test.js
  src/containers/Navigation/Navigation.vue
  src/helpers/query/utils.js
  src/pages/AdminProfile.vue
  src/pages/HomeAdministrator.vue
  src/pages/HomeParticipant.vue
  src/pages/HomeSelector.vue
  src/pages/ProgressReport.vue
  src/pages/ScoreReport.vue
  src/pages/StudentReport.vue
Labels: bug

#1165 Exclude From Scoring Tasks
  src/helpers/reports.js
Labels: enhancement

#1157 Update roam-apps version to 1.2.8
  package-lock.json
  package.json
Labels: task-update

#1167 Reliability Flags Exclusion
  src/helpers/reports.js
  src/pages/ScoreReport.vue
Labels: enhancement
