Repository yeatmanlab/roar-dashboard, pull requests merged in 2025-05, with the labels that each got.

#1159 update progress charts to point to org stats
  src/composables/queries/useAdministrationsStatsQuery.js
  src/composables/queries/useAdministrationsStatsQuery.test.js
  src/pages/ProgressReport.vue
  src/store/auth.js
Labels: bug

#1170 Remove legacy staging deployment workflow
  .github/workflows/deploy-legacy-staging.yml
Labels: enhancement

#1172 Prevent users from editing graphs on individual reports
  src/components/reports/IndividualScoreReportTask.vue
Labels: bug

#1162 Add composite score column
  package-lock.json
  package.json
  src/helpers/query/assignments.js
  src/pages/ScoreReport.vue
Labels: enhancement

#1182 Update outdated task permissions
  src/components/tasks/ManageTasks.vue
  src/components/tasks/ManageVariants.vue
  src/containers/ManageTasks/components/CreateTaskForm.vue
  src/containers/ManageTasks/components/UpdateTaskForm.vue
Labels: bug

#1181 Qualtrics External Tasks Participant ID URL param
  src/components/GameTabs.vue
Labels: enhancement

#1174 Update PA version to 3.0.0
  package-lock.json
  package.json
Labels: enhancement, task-update, [qa] medium priority

#1190 Add product owner review step to production release workflow
  .github/workflows/deploy-production.yml
Labels: enhancement

#1196 Return to participant home after task completion for externally launched assessments
  src/components/tasks/TaskLetter.vue
  src/components/tasks/TaskMultichoice.vue
  src/components/tasks/TaskPA.vue
  src/components/tasks/TaskRan.vue
  src/components/tasks/TaskReadAloud.vue
  src/components/tasks/TaskSRE.vue
  src/components/tasks/TaskSWR.vue
  src/components/tasks/TaskVocab.vue
  src/containers/Navigation/Navigation.vue
  src/pages/HomeSelector.vue
  src/router/sidebarActions.js
Labels: bug

#1202 update icons for in progress and assigned
  src/helpers/reports.js
  src/pages/ProgressReport.vue
Labels: bug

#1204 Add conditional chaining for initialized and registrations
  src/pages/HomeParent.vue
Labels: bug

#1209 Fix Adminstration Assignment queries for ParentView
  src/pages/HomeParent.vue
Labels: bug

#1184 Duplicate Administrations
  src/components/CardAdministration.vue
  src/components/CreateAdministration.vue
  src/constants/routes.js
  src/router/index.js
  src/router/sidebarActions.js
Labels: enhancement
