Repository yeatmanlab/roar-dashboard, pull requests merged in 2025-01, with the labels that each got.

#992 Fixing TOS: Update logic for August detection
  src/pages/HomeParticipant.vue
  src/pages/HomeSelector.vue
Labels: bug

#976 Refactor `<ManageTasks />` component
  cypress/support/commands.js
  cypress/support/component.js
  package-lock.json
  package.json
  src/assets/styles/components/input-group.scss
  src/components/Form/CheckboxInput/CheckBoxInput.test.js
  src/components/Form/CheckboxInput/CheckboxInput.cy.js
  src/components/Form/CheckboxInput/CheckboxInput.vue
  src/components/Form/CheckboxInput/index.js
  src/components/Form/Dropdown/Dropdown.cy.js
  src/components/Form/Dropdown/Dropdown.vue
  src/components/Form/Dropdown/index.js
  src/components/Form/NumberInput/NumberInput.cy.js
  src/components/Form/NumberInput/NumberInput.test.js
  src/components/Form/NumberInput/NumberInput.vue
  src/components/Form/NumberInput/index.js
  src/components/Form/TextInput/TextInput.cy.js
  src/components/Form/TextInput/TextInput.test.js
  src/components/Form/TextInput/TextInput.vue
  src/components/Form/TextInput/index.js
  src/components/PageTitle/PageTitle.vue
  src/components/PageTitle/index.js
  src/components/tasks/ManageTasks.vue
  src/constants/tasks.js
  src/constants/toasts.js
  src/containers/ManageTasks/ManageTasks.cy.js
  src/containers/ManageTasks/ManageTasks.vue
  src/containers/ManageTasks/components/CreateTaskForm.vue
  src/containers/ManageTasks/components/TaskParametersConfigurator.cy.js
  src/containers/ManageTasks/components/TaskParametersConfigurator.vue
  src/containers/ManageTasks/components/TaskParametersConfiguratorRow.cy.js
  src/containers/ManageTasks/components/TaskParametersConfiguratorRow.vue
  src/containers/ManageTasks/components/UpdateTaskForm.vue
  src/containers/ManageTasks/index.js
  src/helpers/convertObjectToParamArray.js
  src/helpers/convertParamArrayToObject.js
  src/helpers/formValidators.js
  src/pages/ManageTasksVariants.vue
  src/styles.css
  src/translations/i18n.js
  vitest.config.js
  vitest.setup.js
Labels: enhancement

#995 Update SWR version to 1.12.13
  package-lock.json
  package.json
Labels: task-update

#1005 CSS minor updates
  src/assets/styles/theme-tailwind.css
  src/components/CardAdministration.vue
  src/components/GameTabs.vue
  src/components/RoarDataTable/RoarDataTable.vue
Labels: bug, design-alignment

#998 Update security headers
  firebase.json
  vite.config.js
Labels: enhancement

#1004 Update Levante Core-tasks
  package-lock.json
  package.json
Labels: task-update, [qa] high priority

#1009 Update roam-apps version to 1.0.9
  cypress/e2e/pre-release-tests/testOpenAdministrations.cy.js
  cypress/fixtures/super-admin/generatedTestTemplate.js
  cypress/support/helper-functions/roam-apps/roamHelpers.js
  cypress/support/helper-functions/roar-letter/letterHelpers.js
  cypress/support/helper-functions/roar-multichoice/multichoiceHelpers.js
  cypress/support/helper-functions/roar-pa/paHelpers.js
  cypress/support/helper-functions/roar-sre/sreHelpers.js
  cypress/support/helper-functions/roar-swr/swrHelpers.js
  cypress/support/helper-functions/roar-syntax/syntaxHelpers.js
  cypress/support/helper-functions/roar-vocab/vocabHelpers.js
  package-lock.json
  package.json
Labels: task-update, [qa] medium priority

#1007 Update ROAV-Crowding version to 1.1.34
  package-lock.json
  package.json
Labels: task-update, [qa] high priority

#1017 Update ROAV-Crowding version to 1.1.35
  package-lock.json
  package.json
Labels: [qa] high priority

#1018 Fix ROAM Apps path and img policy
  .github/workflows/ci.yml
  firebase.json
  src/router/index.js
Labels: bug, dependencies, [qa] high priority
