Repository yeatmanlab/roar-dashboard, pull requests merged in 2025-02, with the labels that each got.

#1016 Update Content-Security-Policy
  firebase.json
Labels: enhancement

#1024 Update SRE version to 1.16.0
  cypress/e2e/participant/old-tests/playButtonGames.cy.js
  cypress/support/helper-functions/roar-pa/paHelpers.js
  cypress/support/helper-functions/roar-sre/sreHelpers.js
  package-lock.json
  package.json
Labels: task-update

#1027 Fix typos and subtable bubbles background
  src/components/reports/IndividualScoreReportTask.vue
  src/components/reports/SubscoreTable.vue
  src/components/reports/tasks/TaskReport.vue
  src/pages/StudentReport.vue
Labels: bug, effort: low, design-alignment

#1031 Fix tag css color placement
  src/components/reports/SubscoreTable.vue
  src/components/reports/TableScoreTag.vue
Labels: bug, design-alignment

#1032 display scores for roam alpaca
  src/containers/Navigation/Navigation.vue
  src/helpers/reports.js
Labels: bug

#1030 Update roam-apps version to 1.0.11
  package-lock.json
  package.json
  src/containers/Navigation/Navigation.vue
Labels: task-update

#1034 Fix tooltip message and grayed color on includedValidityFlags
  src/components/reports/TableScoreTag.vue
  src/helpers/reports.js
  src/pages/ScoreReport.vue
Labels: bug

#1026 update parent sign up error dialog and remove back button post-submission
  src/components/auth/RegisterChildren.vue
  src/pages/RegisterFamilyUsers.vue
Labels: bug

#1039 FIX Pluralize Orgs
  src/pages/RegisterFamilyUsers.vue
  src/pages/RegisterStudents.vue
Labels: bug

#1041 External ROAR tasks open in a new tab and display message
  src/components/GameTabs.vue
  src/translations/en/en-componentTranslations.json
  src/translations/en/us/en-us-componentTranslations.json
  src/translations/es/co/es-co-componentTranslations.json
  src/translations/es/es-componentTranslations.json
Labels: enhancement

#1037 Update `feat/project-config` from `main`
  .github/actions/deploy/action.yml
  .github/workflows/ci.yml
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-staging.yml
  cypress/support/helper-functions/roar-pa/paHelpers.js
  cypress/support/helper-functions/roar-sre/sreHelpers.js
  firebase/admin/firebase.json
  package-lock.json
  package.json
  src/components/auth/RegisterChildren.vue
  src/components/reports/IndividualScoreReportTask.vue
  src/components/reports/TableScoreTag.vue
  src/components/reports/tasks/TaskReport.vue
  src/containers/Navigation/Navigation.vue
  src/helpers/reports.js
  src/pages/RegisterFamilyUsers.vue
  src/pages/StudentReport.vue
  src/router/index.js
  vite.config.js
Labels: enhancement
